version: '3'

services:
  whoami:
    image: containous/whoami:latest
    container_name: whoami
    hostname: whoami
    restart: unless-stopped

  caddy:
    build: ./
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    env_file: caddy.env
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/docker/caddy/data:/data
      - /var/docker/caddy/config:/config
